[theme]
base="light"
primaryColor="#6A5ACD"  # A lavender shade
backgroundColor="#E6E6FA"  # Light lavender
secondaryBackgroundColor="#D8BFD8"  # Another soft lavender shade
textColor="#4B0082"  # Darker purple for contrast
